[CVE-2021-42550] Update Logback to version 1.2.9
splunk/splunk-library-javalogging pull request #233
Opened 2021-12-20 20:55 UTC by sotty

In response to:
https://cve.report/CVE-2021-42550

2021-12-20 21:35 UTC, ranma2913 commented
Another link: https://nvd.nist.gov/vuln/detail/CVE-2021-42550

2021-12-20 21:47 UTC, ranma2913 requested changes

2021-12-20 21:47 UTC, ranma2913 commented on pom.xml
> +        <!-- https://jira.qos.ch/browse/LOGBACK-1591 -->
```suggestion
        <!-- CVE-2021-42550: https://nvd.nist.gov/vuln/detail/CVE-2021-42550 -->
```

2021-12-20 21:47 UTC, ranma2913 commented on pom.xml
> +            <version>${logback.version}</version>
Thanks. I really like using a property here since there's several dependencies with the same version.

2021-12-20 23:19 UTC, sotty commented on pom.xml
> +        <!-- https://jira.qos.ch/browse/LOGBACK-1591 -->
thank you - I have updated the link

2021-12-20 23:36 UTC, ranma2913 approved these changes

2021-12-20 23:36 UTC, ranma2913 commented on pom.xml
> +        <!-- https://jira.qos.ch/browse/LOGBACK-1591 -->
Great. Thanks

2021-12-21 19:21 UTC, sotty commented
@ranma2913 @fantavlik Are there any next steps, or concerns, on getting this PR approved and merged? 
Thank you in advance

2021-12-22 14:24 UTC, sotty commented
I have found and signed the contributor agreement - should I also open an Issue for this PR?

2021-12-22 16:03 UTC, sotty commented
Rebased + squashed to keep the history linear

2021-12-23 19:54 UTC, merged

2021-12-23 20:05 UTC, fantavlik commented
Thanks @sotty! This is out as v1.11.4 now.